services:
  backend:
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: hezzltest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - backend-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hezzltest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - backend-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-network

  nats:
    image: nats:latest
    command: "--js"
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - backend-network

  clickhouse:
    build:
      context: .
      dockerfile: clickhouse.Dockerfile
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
  clickhouse_data: